# Generated by Django 5.0 on 2023-12-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.TextField(verbose_name='mehsulun rengi')),
            ],
            options={
                'verbose_name': 'reng',
                'verbose_name_plural': 'rengler',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.TextField(verbose_name='mehsulun olcusu')),
            ],
            options={
                'verbose_name': 'olcu',
                'verbose_name_plural': 'olculer',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='mehsulun adi')),
                ('price', models.FloatField(verbose_name='mehsulun qiymeti')),
                ('description_L', models.TextField(verbose_name='kicik movzu')),
                ('description_B', models.TextField(verbose_name='boyuk movzu')),
                ('rating', models.FloatField(verbose_name='reyting')),
                ('information', models.TextField(verbose_name='mehsul haqqinda')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.category')),
                ('color', models.ManyToManyField(blank=True, null=True, to='my_app.color')),
                ('size', models.ManyToManyField(blank=True, null=True, to='my_app.size')),
            ],
            options={
                'verbose_name': 'mehsul',
                'verbose_name_plural': 'mehsullar',
                'ordering': ('-created_at',),
            },
        ),
    ]
