# Generated by Django 4.2.5 on 2023-12-20 14:00

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_product_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='ad ve soyad')),
                ('email', models.CharField(max_length=255, verbose_name='email adress')),
                ('subject', models.CharField(max_length=255, verbose_name='movzu')),
                ('mesage', models.TextField(verbose_name='mesaj')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contactlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Partniors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_partniors)),
            ],
            options={
                'verbose_name': 'partnior sekil',
                'verbose_name_plural': 'partnior sekiller',
                'ordering': ('-created_at',),
            },
        ),
    ]
