# Generated by Django 4.2.5 on 2023-12-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_contact_partniors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='ad')),
                ('surname', models.CharField(max_length=255, verbose_name='soyad')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(max_length=255, verbose_name='telefon')),
                ('adress1', models.CharField(max_length=255, verbose_name='adress 1')),
                ('adress2', models.CharField(max_length=255, verbose_name='adress 2')),
                ('country', models.CharField(choices=[('usa', 'Amerika'), ('az', 'Azerbaijan'), ('eu', 'Europa'), ('as', 'Asia')], max_length=255, verbose_name='olke adlari')),
                ('city', models.CharField(max_length=255, verbose_name='sheher adi')),
                ('state', models.CharField(max_length=255, verbose_name='dovlet')),
                ('zipcode', models.CharField(max_length=255, verbose_name='olke kodu')),
            ],
            options={
                'verbose_name': 'checkout',
                'verbose_name_plural': 'checkout',
                'ordering': ('name',),
            },
        ),
    ]
