# Generated by Django 4.2.5 on 2023-12-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_blog_alter_product_color_alter_product_size_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
