# Generated by Django 4.2.5 on 2024-01-05 16:55

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_remove_partniors_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('text', models.TextField(verbose_name='metn')),
                ('discount', models.TextField(verbose_name='endirim')),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_special_offer)),
            ],
            options={
                'verbose_name': 'xususi teklif',
                'verbose_name_plural': 'xususi teklifler',
                'ordering': ('-created_at',),
            },
        ),
    ]
