# Generated by Django 4.2.5 on 2024-01-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
