# Generated by Django 5.0 on 2024-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sosial_name', models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('tiktok', 'Tiktok')], max_length=255, verbose_name='sosial media hesabi')),
                ('sosial_link', models.TextField(verbose_name='sosial media linki')),
            ],
            options={
                'verbose_name': 'sosial media hesabi',
                'verbose_name_plural': 'sosial media hesablari',
                'ordering': ('sosial_name',),
            },
        ),
    ]
