# Generated by Django 5.0 on 2024-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_sosialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='adi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='adi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='adi'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_az',
            field=models.TextField(null=True, verbose_name='mehsulun rengi'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.TextField(null=True, verbose_name='mehsulun rengi'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='mehsulun rengi'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_B_az',
            field=models.TextField(null=True, verbose_name='boyuk movzu'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_B_en',
            field=models.TextField(null=True, verbose_name='boyuk movzu'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_B_ru',
            field=models.TextField(null=True, verbose_name='boyuk movzu'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_L_az',
            field=models.TextField(null=True, verbose_name='kicik movzu'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_L_en',
            field=models.TextField(null=True, verbose_name='kicik movzu'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_L_ru',
            field=models.TextField(null=True, verbose_name='kicik movzu'),
        ),
        migrations.AddField(
            model_name='product',
            name='information_az',
            field=models.TextField(null=True, verbose_name='mehsul haqqinda'),
        ),
        migrations.AddField(
            model_name='product',
            name='information_en',
            field=models.TextField(null=True, verbose_name='mehsul haqqinda'),
        ),
        migrations.AddField(
            model_name='product',
            name='information_ru',
            field=models.TextField(null=True, verbose_name='mehsul haqqinda'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='mehsulun adi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='mehsulun adi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='mehsulun adi'),
        ),
        migrations.AddField(
            model_name='slider',
            name='text_az',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='slider',
            name='text_en',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='slider',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='basliq'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='basliq'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='basliq'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='text_az',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='text_en',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
    ]
